### PR TITLE
Propagating error upstream + Random eviction Fix

### LINKED ISSUE #525: investigate and fix correlation id was not found
### Interactsh version:

main | dev

### Current Behavior:

- interactsh client randomly exits with fatal error
```console
  [FTL] The correlation id was not found (probably evicted due to inactivity)
```
- https://github.com/projectdiscovery/interactsh/pull/524 temporarily fixes the issue by not exiting and only printing but the actual error is different . This is not reproducible in local machines but almost always visible in gh actions . probably something related to runners ?
- Ref: https://github.com/projectdiscovery/nuclei/actions/runs/4600751855/jobs/8127749422

### Expected Behavior:

- no error + no fatal exit

### Anything else:

- https://github.com/projectdiscovery/nuclei/issues/3507

### PR DESCRIPTION
**Pull request by Mzack9999**
## Description
This PR implements the following changes:
- Changes `StartPolling` to block and return on error (similarly to `http.Serve()`) and propagate upstream internal descriptive errors (current implementations need to wrap it into go routine to be asynchronous
- Fixes a rare random `atomic.Value` state change that caused asynchronous server read to face early eviction due to the state being `Polling` at iteration check, but turned to `Idle/Closed` via `StopPolling()`/`Close()` (Closes #525)

Note: the first change represent a breaking change

### CODE REVIEW

**Review by ShubhamRasal — APPROVED** [review]
lgtm 😃 

Notes:
- we have to enable, host swap so container can use it directly
- enabling swap may degrade performance, https://docs.docker.com/engine/install/troubleshoot/#kernel-cgroup-swap-limit-capabilities

**Comment by Mzack9999** [comment]
Host swap should be already enabled at OS level. Do we need to add any particular capability/permission to docker or the two conf flags are enough?

**Comment by ShubhamRasal** [comment]
> Host swap should be already enabled at OS level. Do we need to add any particular capability/permission to docker or the two conf flags are enough?

I see, on the servers that swap is not enabled, we may to enable swap before deploying these changes

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
We are currently running interactsh server with this branch at hackwithautomation.com

**Pull request merged**
