### PR TITLE
please support multiple public ip ipAddress #417 2022-12-07

### LINKED ISSUE #417: Add support multiple public ips
## Description
A server might be configured to listen on multiple public IP addresses. Interactsh should be able to support various ips on the command line to use in DNS responses.

### PR DESCRIPTION
**Pull request by hktalent**
support multiple public ip ipAddress - Closes #417
Now, based on the development of interactsh, it already supports the analysis of multiple Internet ip
```
$ dig A www.sina.com.cn

;; ANSWER SECTION:
www.sina.com.cn.	28	IN	CNAME	spool.grid.sinaedge.com.
spool.grid.sinaedge.com. 45	IN	CNAME	ww1.sinaimg.cn.w.alikunlun.com.
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.92.241
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.19.242
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	183.223.15.219
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	183.223.15.223
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	183.223.15.221
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	183.223.15.218
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	183.223.15.222
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	183.223.15.225
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.19.238
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.19.244
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.19.243
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.19.240
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.19.241
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.92.236
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.92.240
ww1.sinaimg.cn.w.alikunlun.com.	28 IN	A	36.170.92.237
```

### CODE REVIEW

**Review by Mzack9999 — APPROVED** [review]
lgtm - requires functional testing with multiple IPs

**Review by ehsandeep — COMMENTED** [review]
@hktalent @Mzack9999 do we know the expected input for using this feature?

```console
./interactsh-server -d hackwithautomation.com -ip 157.230.223.165,157.230.223.164

    _       __                       __       __  
   (_)___  / /____  _________ ______/ /______/ /_ 
  / / __ \/ __/ _ \/ ___/ __ '/ ___/ __/ ___/ __ \
 / / / / / /_/  __/ /  / /_/ / /__/ /_(__  ) / / /
/_/_/ /_/\__/\___/_/   \__,_/\___/\__/____/_/ /_/ 1.0.7

		projectdiscovery.io

[INF] Loading existing SSL Certificate for:  [*.hackwithautomation.com, hackwithautomation.com]
[INF] Listening with the following services:
[ERR] Could not listen for TCP DNS on 0.0.0.0:53 (listen tcp 0.0.0.0:53: bind: address already in use)
[ERR] Could not listen for UDP DNS on 0.0.0.0:53 (listen udp 0.0.0.0:53: bind: address already in use)
1.6758636439819584e+09	info	maintenance	started background certificate maintenance	{"cache": "0xc0000deaf0"}
[LDAP] Listening on TCP 0.0.0.0:389
[SMTPS] Listening on TCP 0.0.0.0:587
[HTTP] Listening on TCP 0.0.0.0:80
[DNS] Listening on UDP 0.0.0.0:53
[DNS] Listening on TCP 0.0.0.0:53
[HTTPS] Listening on TCP 0.0.0.0:443
[SMTP] Listening on TCP 0.0.0.0:25
[FTL] The UDP DNS service has unexpectedly stopped
```

**Comment by hktalent** [comment]
At present, I haven't practiced in multi-ip (cluster), and I don't know what to expect

**Comment by ehsandeep** [comment]
Closing as the feature is unclear in its current state.

**Pull request closed without merging**
